version: '3.3'
services:
  db:
    image: mysql:latest
    restart: always
    volumes:
      - "./mysql_data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
      #MYSQL_DATABASE: 'my_db'
      #MYSQL_USER: 'user'
      #MYSQL_PASSWORD: '1234'
    ports:
      - '3306:3306'
    expose:
      - '3306'
