version: "3"
services:
  php5_www:
    build: ./
    container_name: php5.docker
    volumes:
      #- ./www:/var/www/html
      - /srv/http:/var/www/html/public
      - ~/.ssh:/root/.ssh
    ports:
      - "81:80"
    environment:
      WEB_DOCUMENT_ROOT: /var/www/html/public
    networks:
      my_network:
        ipv4_address: 172.100.0.12
networks:
  my_network:
    external: true
